import { StyleSheet, Dimensions, Platform } from 'react-native';
import StyleConstant from './StyleConstant';

const { width, height } = Dimensions.get("window");

export default StyleSheet.create({
	mainContainer: {
		flex: 1,
		marginBottom: global.FULL_DISPLAY ? 0 : 0,
	},
	container: {
		paddingHorizontal: global.Gap_15,
	},
	tabBar: {
		height: global.Tab_Bar_Height,
		paddingVertical: global.Gap_10,
		backgroundColor: global.TAB_BG_COLOR,
	},
	notificationMainView: {
		top: global.Gap_20,
		left: global.Gap_15,
		right: global.Gap_15,
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "flex-start",
		position: "absolute",
		paddingHorizontal: global.Gap_15,
		paddingVertical: global.Gap_15,
		backgroundColor: global.WHITE_COLOR,
		borderWidth: 1,
		borderRadius: global.Gap_5,
		borderColor: global.LIGHT_GREY_COLOR,
		zIndex: 9999,
	},
	smallPlayerViewView: {
		bottom: global.Gap_5,
		left: global.Gap_10,
		right: global.Gap_10,
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "flex-start",
		position: "absolute",
		paddingHorizontal: global.Gap_10,
		paddingVertical: global.Gap_10,
		backgroundColor: global.TAB_BG_COLOR,
		borderRadius: global.Gap_5,
		zIndex: 9999,
	},
	activityIndicator: {
		width: "100%",
		height: "100%",
		top: 0,
		left: 0,
		right: 0,
		bottom: 0,
		position: "absolute",
		//backgroundColor: "rgba(0,0,0,0.6)",
		zIndex: 9999,
		justifyContent: "center",
		alignItems: "center"
	},
	SecoundActivityIndicator: {
		width: "100%",
		height: "100%",
		top: 0,
		left: 0,
		right: 0,
		bottom: 0,
		position: "absolute",
		backgroundColor: "rgba(0,0,0,0.6)",
		zIndex: 9999,
		justifyContent: "center",
		alignItems: "center"
	},
	copyLinkView: {
		marginTop: global.Gap_10,
		width: "100%",
		height: "100%",
		top: 0,
		left: 0,
		right: 0,
		bottom: 0,
		position: "absolute",
		//backgroundColor: "rgba(0,0,0,0.6)",
		zIndex: 9999,
		justifyContent: "center",
		alignItems: "center"
	},
	noInternetMainView: {
		width: '100%',
		justifyContent: 'center',
		alignItems: 'center',
		position: "relative",
		backgroundColor: global.WHITE_COLOR,
		paddingVertical: global.Gap_5,
	},
	topBar: {
		height: global.Top_Bar_Height,
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "flex-start",
		paddingHorizontal: global.Gap_15,
		backgroundColor: global.WHITE_COLOR,
	},
	topBarTitle: {
		left: 0,
		right: 0,
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
		position: "absolute",
	},
	splashScreenImage: {
		height: (global.IS_IPAD ? 240 : 120),
		width: (global.IS_IPAD ? 240 : 120),
		resizeMode: "cover", // cover,contain,stretch,repeat,center
	},
	splashScreenLogo: {
		height: height,
		width: width,
		resizeMode: "cover", // cover,contain,stretch,repeat,center
	},
	topViewImage: {
		height: global.FULL_DISPLAY ? (global.IS_IPAD ? 200 : 110) : (global.IS_IPAD ? 150 : 90),
		width: width,
		resizeMode: "cover", // cover,contain,stretch,repeat,center
	},
	qiCoilTopViewImage: {
		height: global.FULL_DISPLAY ? (global.IS_IPAD ? 240 : 140) : (global.IS_IPAD ? 190 : 120),
		width: width,
		resizeMode: "cover", // cover,contain,stretch,repeat,center
	},
	albumsListTopViewImage: {
		height: global.FULL_DISPLAY ? (global.IS_IPAD ? 200 : 100) : (global.IS_IPAD ? 150 : 80),
		width: width,
		resizeMode: "cover", // cover,contain,stretch,repeat,center
	},
	splashIntroSlideView: {
		width: width - (global.IS_IPAD ? 200 : 100),
		height: width - (global.IS_IPAD ? 200 : 100),
		alignItems: 'center',
		// justifyContent: 'center',
		// position: "relative",
		backgroundColor: "transparent",
		//backgroundColor: global.RED_COLOR,
	},
	splashIntroSlideLogoView: {
		// marginTop: global.FULL_DISPLAY ? (global.IS_IPAD ? 100 : 70) : (global.IS_IPAD ? 80 : 50),
		alignItems: 'center',
		justifyContent: 'center',
	},
	splashIntroSlideImage: {
		marginTop: global.FULL_DISPLAY ? (global.IS_IPAD ? 110 : 80) : (global.IS_IPAD ? 80 : 50),
		marginLeft: (width - (width - (global.IS_IPAD ? 200 : 100))),
		width: width - (global.IS_IPAD ? 200 : 100),
		height: width - (global.IS_IPAD ? 200 : 100),
		//borderRadius: 10,
		resizeMode: "cover", // cover,contain,stretch,repeat,center
	},
	splashIntroLogoImage: {
		height: (global.IS_IPAD ? 300 : 200),
		width: (global.IS_IPAD ? 300 : 200),
		//borderRadius: 10,
		overflow: "hidden",
		resizeMode: "contain", // cover,contain,stretch,repeat,center
	},
	splashIntroTextView: {
		marginLeft: (width - (width - (global.IS_IPAD ? 200 : 100))),
		height: width - (global.IS_IPAD ? 200 : 100) - (global.IS_IPAD ? 110 : global.FULL_DISPLAY ? 70 : 120),
		width: '100%',
		alignItems: 'center',
		justifyContent: 'center',
		// backgroundColor: global.RED_COLOR,
	},
	loginUserImage: {
		width: (global.IS_IPAD ? 150 : 90),
		height: (global.IS_IPAD ? 150 : 90),
		backgroundColor: global.FULL_LIGHT_GREY_COLOR,
		alignItems: 'center',
		justifyContent: 'center',
		borderRadius: (global.IS_IPAD ? 150 : 90),
		resizeMode: "contain", // cover,contain,stretch,repeat,center
	},
	loginInputView: {
		paddingVertical: (global.IS_IPAD ? 15 : 10),
		borderBottomWidth: 1,
		justifyContent: "center",
		marginHorizontal: (global.IS_IPAD ? 60 : 40),
		borderColor: global.DRAK_DEFAULT_COLOR,
	},
	loginInput: {
		fontSize: (global.IS_IPAD ? 24 : 14),
		fontFamily: global.DEFAULT_FONT,
		color: global.BLACK_COLOR,
		alignItems: "flex-start",
		paddingVertical: 0,
		height: (global.IS_IPAD ? 70 : 40),
	},
	searchInput: {
		fontSize: (global.IS_IPAD ? 24 : 14),
		fontFamily: global.DEFAULT_FONT,
		color: global.BLACK_COLOR,
		alignItems: "flex-start",
		paddingVertical: 0,
		height: (global.IS_IPAD ? 70 : 40),
		// width: "100%",
	},
	subscribeContinueButton: {
		height: (global.IS_IPAD ? 60 : 45),
		width: "70%",
		borderRadius: (global.IS_IPAD ? 50 : 30),
		alignItems: "center",
		justifyContent: "center",
		backgroundColor: global.WHITE_COLOR,
	},

	creatPlayListInput: {
		fontSize: (global.IS_IPAD ? 28 : 18),
		fontFamily: global.DEFAULT_FONT,
		color: global.WHITE_COLOR,
		alignItems: "flex-start",
		paddingVertical: 0,
	},
	helpSupportInput: {
		fontSize: (global.IS_IPAD ? 26 : 16),
		fontFamily: global.DEFAULT_FONT,
		color: global.BLACK_COLOR,
		alignItems: "flex-start",
		paddingVertical: 0,
	},
	helpSupportDescriprion: {
		height: (global.IS_IPAD ? 300 : 180),
		fontSize: (global.IS_IPAD ? 26 : 16),
		fontFamily: global.DEFAULT_FONT,
		color: global.BLACK_COLOR,
		alignItems: "flex-start",
		textAlignVertical: "top",
		paddingVertical: 0,
	},
	searchInput: {
		fontSize: (global.IS_IPAD ? 26 : 16),
		fontFamily: global.DEFAULT_FONT,
		color: global.BLACK_COLOR,
		alignItems: "flex-start",
		paddingVertical: 0,
	},
	loginButton: {
		height: (global.IS_IPAD ? 60 : 40),
		alignItems: "center",
		justifyContent: "center",
		backgroundColor: global.DRAK_BLUE_COLOR,
	},
	loginGoogleButton: {
		height: (global.IS_IPAD ? 65 : 45),
		width: "100%",
		// alignItems: "center",
		justifyContent: "center",
	},
	verificationImg: {
		height: (global.IS_IPAD ? 300 : 200),
		width: width,
		resizeMode: "cover", // cover,contain,stretch,repeat,center
	},
	upgradeMembershipImg: {
		height: (global.IS_IPAD ? 250 : 150),
		width: width,
		resizeMode: "contain", // cover,contain,stretch,repeat,center
	},
	viewUserImage: {
		width: (global.IS_IPAD ? 220 : 110),
		height: (global.IS_IPAD ? 220 : 110),
		backgroundColor: global.FULL_LIGHT_GREY_COLOR,
		alignItems: 'center',
		justifyContent: 'center',
		borderRadius: (global.IS_IPAD ? 110 : 55),
		resizeMode: "contain", // cover,contain,stretch,repeat,center
	},
	viewProfileMypostBtn: {
		width: (width - global.Gap_15 - global.Gap_15 - global.Gap_15 - global.Gap_10 - global.Gap_10) / 3,
		paddingVertical: (global.IS_IPAD ? 15 : 10),
		alignItems: 'center',
		justifyContent: 'center',
		borderRadius: (global.IS_IPAD ? 10 : 7)
	},
	profileTabBtn: {
		width: (width - global.Gap_15 - global.Gap_15 - global.Gap_15 - global.Gap_10 - global.Gap_10 - global.Gap_10) / 3,
		paddingVertical: (global.IS_IPAD ? 15 : 10),
		alignItems: 'center',
		justifyContent: 'center',
		borderRadius: (global.IS_IPAD ? 10 : 7)
	},
	viewWantedCarBtn: {
		width: (width - global.Gap_15 - global.Gap_15 - global.Gap_15) / 2,
		paddingVertical: (global.IS_IPAD ? 15 : 10),
		alignItems: 'center',
		justifyContent: 'center',
		borderRadius: (global.IS_IPAD ? 10 : 7)
	},
	verifiedImageView: {
		position: "absolute",
		top: -global.Gap_5,
		right: -global.Gap_5,
	},
	userSettingSubView: {
		flexDirection: "row",
		justifyContent: "center",
		alignItems: "center",
		paddingHorizontal: (global.IS_IPAD ? 20 : 15),
		paddingVertical: (global.IS_IPAD ? 15 : 10),
		borderBottomWidth: 1,
		borderColor: LIGHT_GREY_COLOR,
		backgroundColor: WHITE_COLOR,
	},
	cardSetting: {
		marginTop: 5,
		fontSize: (global.IS_IPAD ? 24 : 14),
		fontFamily: global.DEFAULT_FONT,
		color: global.BLACK_COLOR,
		alignItems: "flex-start",
		paddingVertical: 0,
	},
	invoiceButton: {
		width: (global.IS_IPAD ? 160 : 80),
		height: (global.IS_IPAD ? 44 : 24),
		alignItems: 'center',
		justifyContent: 'center',
		borderRadius: global.Gap_20,
	},
	fatchedPostImages: {
		marginTop: (global.IS_IPAD ? 20 : 10),
		marginLeft: (global.IS_IPAD ? 20 : 10),
		width: (width - ((global.IS_IPAD ? 20 : 10) * 5)) / 4,
		height: (width - ((global.IS_IPAD ? 20 : 10) * 5)) / 4,
		backgroundColor: global.FULL_LIGHT_GREY_COLOR,
		alignItems: 'center',
		justifyContent: 'center',
		resizeMode: "contain",
	},
	PostImagesDelete: {
		top: (global.IS_IPAD ? 10 : 7.5),
		right: -(global.IS_IPAD ? 10 : 7.5),
		width: (global.IS_IPAD ? 30 : 20),
		height: (global.IS_IPAD ? 30 : 20),
		borderRadius: (global.IS_IPAD ? 30 : 20),
		position: "absolute",
		alignItems: "center",
		justifyContent: "center",
		alignSelf: "center",
		flexDirection: "row",
		opacity: 0.5,
		backgroundColor: global.BLACK_COLOR,
	},
	urlKontentMain: {
		flexDirection: "row",
		justifyContent: "space-between",
		alignItems: "flex-start",
		backgroundColor: WHITE_COLOR,
		borderBottomWidth: 1,
		borderColor: LIGHT_GREY_COLOR,
	},
	urlKontentSubLeft: {
		flex: 0.2,
		paddingHorizontal: (global.IS_IPAD ? 20 : 15),
		paddingVertical: (global.IS_IPAD ? 15 : 10),
	},
	urlKontentSubRight: {
		flex: 0.8,
		alignItems: "flex-end",
		justifyContent: "center",
		paddingHorizontal: (global.IS_IPAD ? 15 : 10),
		paddingVertical: (global.IS_IPAD ? 15 : 10),
	},
	fetchedPostData: {
		width: '100%',
		fontSize: (global.IS_IPAD ? 24 : 14),
		fontFamily: global.DEFAULT_FONT,
		color: global.DEFAULT_COLOR,
		justifyContent: "center",
		alignItems: "center",
		textAlign: "right",
		paddingVertical: 0,
	},
	inputFeedback: {
		//height: (global.IS_IPAD ? 700 : 400),
		fontSize: (global.IS_IPAD ? 24 : 14),
		fontFamily: global.DEFAULT_FONT,
		paddingHorizontal: global.Gap_10,
		color: global.BLACK_COLOR,
		alignItems: "flex-start",
		paddingVertical: 0,
		backgroundColor: global.WHITE_COLOR,
	},
	inputCreateRegnoPost: {
		marginHorizontal: (global.IS_IPAD ? 20 : 15),
		height: (global.IS_IPAD ? 105 : 75),
		width: width - (global.IS_IPAD ? 40 : 30) - (global.IS_IPAD ? 40 : 30),
		fontSize: (global.IS_IPAD ? 50 : 40),
		// lineHeight: (global.IS_IPAD ? 56 : 44),
		fontFamily: global.UK_NUMBER_PLATE_FONT,
		color: global.BLACK_COLOR,
		alignItems: 'center',
		justifyContent: 'center',
		paddingVertical: 0,
		// backgroundColor: global.WHITE_COLO
	},
	postListItem: {
		//marginLeft: global.Gap_5,
		width: width - global.Gap_5 - global.Gap_5,
		position: "relative",
		marginTop: global.Gap_5,
		marginLeft: global.Gap_5,
		borderRadius: global.Gap_10,
		alignItems: 'center',
		justifyContent: 'center',
	},
	postListImage: {
		width: (width - global.Gap_30) / 3,
		height: (((width - global.Gap_30 - global.Gap_25) / 3) - global.Gap_30),
		// height: (((width - global.Gap_30 - global.Gap_30) / 3) * 9) / 16,
		backgroundColor: global.FULL_LIGHT_GREY_COLOR,
		alignItems: 'flex-start',
		justifyContent: 'flex-start',
		resizeMode: "cover", // cover,contain,stretch,repeat,center
	},
	homeRegNo: {
		fontFamily: global.UK_NUMBER_PLATE_FONT,
		fontSize: (global.IS_IPAD ? 30 : 20),
		lineHeight: (global.IS_IPAD ? 36 : 24),
		color: BLACK_COLOR,
	},
	postListView: {
		//marginLeft: global.Gap_5,
		width: width - global.Gap_5 - global.Gap_5,
		position: "relative",
		marginTop: global.Gap_5,
		marginLeft: global.Gap_5,
		borderRadius: global.Gap_10,
		alignItems: 'center',
		justifyContent: 'center',
	},
	postListViewsItemImage: {
		width: (width - global.Gap_30) / 3,
		height: (((width - global.Gap_30 - global.Gap_25) / 3) - global.Gap_30),
		// height: (((width - global.Gap_30 - global.Gap_30) / 3) * 9) / 16,
		backgroundColor: global.FULL_LIGHT_GREY_COLOR,
		alignItems: 'flex-start',
		justifyContent: 'flex-start',
		resizeMode: "cover", // cover,contain,stretch,repeat,center
	},
	homeViewRegNo: {
		fontFamily: global.UK_NUMBER_PLATE_FONT,
		fontSize: (global.IS_IPAD ? 28 : 18),
		lineHeight: (global.IS_IPAD ? 34 : 22),
		color: BLACK_COLOR,
	},
	postDetailsPostImage: {
		flex: 1,
		width: width,
		alignItems: 'center',
		justifyContent: 'center',
		overflow: "hidden",
		position: "relative",
		backgroundColor: "transparent",
		//backgroundColor: global.RED_COLOR,
	},
	postDetailsImg: {
		marginHorizontal: 15,
		width: width,
		height: (global.IS_IPAD ? 400 : 250),
		overflow: "hidden",
		resizeMode: "contain", // cover,contain,stretch,repeat,center
	},
	carDetailsBackButton: {
		top: global.FULL_DISPLAY ? (global.IS_IPAD ? 70 : 40) : (global.IS_IPAD ? 50 : 20),
		left: (global.IS_IPAD ? 15 : 10),
		position: "absolute",
		alignItems: "center",
		justifyContent: "center",
		alignSelf: "center",
		width: (global.IS_IPAD ? 60 : 40),
		height: (global.IS_IPAD ? 60 : 40),
		borderRadius: (global.IS_IPAD ? 30 : 20),
		backgroundColor: "rgba(0,0,0,0.3)",
	},
	carDetailsImageSubView: {
		bottom: (global.IS_IPAD ? 50 : 30),
		left: (global.IS_IPAD ? 30 : 20),
		width: (global.IS_IPAD ? 70 : 50),
		height: (global.IS_IPAD ? 40 : 30),
		borderRadius: (global.IS_IPAD ? 10 : 5),
		position: "absolute",
		alignItems: "center",
		justifyContent: "center",
		alignSelf: "center",
		flexDirection: "row",
		// opacity: 0.3,
		backgroundColor: global.WHITE_COLOR,
	},
	usrDtlablurImage: {
		width: width,
		height: (global.IS_IPAD ? 120 : 80),
		alignItems: 'center',
		justifyContent: 'center',
		resizeMode: "cover", // cover,contain,stretch,repeat,center
	},
	carDetailsUserImage: {
		width: (global.IS_IPAD ? 60 : 40),
		height: (global.IS_IPAD ? 60 : 40),
		backgroundColor: global.FULL_LIGHT_GREY_COLOR,
		alignItems: 'center',
		justifyContent: 'center',
		borderRadius: (global.IS_IPAD ? 110 : 55),
		resizeMode: "contain", // cover,contain,stretch,repeat,center
	},
	bidImage: {
		height: (global.IS_IPAD ? 400 : 300),
		width: width,
		resizeMode: "cover", // cover,contain,stretch,repeat,center
	},
	bidProfileUser: {
		width: (global.IS_IPAD ? 40 : 30),
		height: (global.IS_IPAD ? 40 : 30),
		backgroundColor: global.FULL_LIGHT_GREY_COLOR,
		alignItems: 'center',
		justifyContent: 'center',
		borderRadius: (global.IS_IPAD ? 40 : 30),
		resizeMode: "contain",
	},
	carDetailsVerifiedImage: {
		position: "absolute",
		bottom: -(global.IS_IPAD ? 10 : 6),
		right: -(global.IS_IPAD ? 10 : 6),
	},

	checkYourCarMainButton: {
		flex: 0.5,
		justifyContent: "center",
		alignItems: "center",
		borderRadius: (global.IS_IPAD ? 15 : 10),
		paddingVertical: (global.IS_IPAD ? 17 : 12),
		// backgroundColor: FULL_LIGHT_DEFAULT_COLOR,
	},
	checkYourCarInputview: {
		height: (global.IS_IPAD ? 100 : 70),
		width: width / 1.4,
		fontFamily: global.DEFAULT_FONT,
		fontSize: (global.IS_IPAD ? 40 : 30),
		// lineHeight: (global.IS_IPAD ? 46 : 34),
		textAlign: "center",
		fontWeight: "bold",
		paddingVertical: 0,
		borderWidth: 1,
		borderRadius: (global.IS_IPAD ? 15 : 10),
		borderColor: global.LIGHT_GREY_COLOR,
		color: DRAK_GREY_COLOR,
		backgroundColor: FULL_LIGHT_DEFAULT_COLOR,
	},
	valuationSubViews: {
		paddingLeft: (global.IS_IPAD ? 15 : 10),
		paddingVertical: (global.IS_IPAD ? 12 : 7),
		backgroundColor: DEFAULT_COLOR,
		borderTopRightRadius: (global.IS_IPAD ? 15 : 10),
		borderBottomRightRadius: (global.IS_IPAD ? 15 : 10),
		backgroundColor: global.LIGHT_ORANGE_COLOR,
	},
	postItemPeople: {
		width: width,
		position: "relative",
		marginVertical: global.Gap_5,
		alignSelf: "center",
	},
	emptyList: {
		width: '100%',
		position: "relative",
		flexDirection: "row",
		justifyContent: "center",
		alignItems: "center",
	},
	postSearchMainBtn: {
		flex: 0.5,
		justifyContent: "center",
		alignItems: "center",
		// borderWidth: 1,
		// shadowColor: global.BLACK_COLOR,
		// shadowOpacity: 0.5,
		// shadowRadius: (global.IS_IPAD ? 15 : 10),
		// shadowOffset: { height: 2, width: 2 },
		borderRadius: (global.IS_IPAD ? 15 : 10),
		// borderColor: global.WHITE_COLOR,
		paddingVertical: (global.IS_IPAD ? 15 : 10),
	},
	bidTabBtn: {
		flex: 0.5,
		justifyContent: "center",
		alignItems: "center",
		// borderWidth: 1,
		shadowColor: global.BLACK_COLOR,
		shadowOpacity: 0.5,
		shadowRadius: (global.IS_IPAD ? 15 : 10),
		shadowOffset: { height: 2, width: 2 },
		borderRadius: (global.IS_IPAD ? 15 : 10),
		borderColor: global.WHITE_COLOR,
		paddingVertical: (global.IS_IPAD ? 15 : 10),
	},
	userSearchInput: {
		height: (global.IS_IPAD ? 50 : 30),
		fontFamily: global.DEFAULT_FONT,
		fontSize: (global.IS_IPAD ? 26 : 16),
		// lineHeight: (global.IS_IPAD ? 32 : 20),
		paddingHorizontal: (global.IS_IPAD ? 10 : 5),
		color: global.WHITE_COLOR,
		alignItems: "center",
		paddingVertical: 0,
		// backgroundColor: global.FULL_LIGHT_GREY_COLOR,
	},
	chatListItems: {
		marginTop: global.Gap_5,
		width: width,
		position: "relative",
		marginVertical: global.Gap_5,
		alignSelf: "center",
	},
	chatListblurImages: {
		width: width,
		height: (global.IS_IPAD ? 100 : 60),
		alignItems: 'center',
		justifyContent: 'center',
		resizeMode: "cover", // cover,cover,stretch,repeat,center
	},
	loginBackgroundImages: {
		width: width,
		height: height + 20,
		alignItems: 'center',
		justifyContent: 'center',
		resizeMode: "cover", // cover,contain,stretch,repeat,center
	},
	adminTimeTexts: {
		width: "60%",
		flexDirection: 'column',
		alignItems: "center",
		justifyContent: "center",
		padding: global.Gap_5,
		alignSelf: "center",
	},
	msgTime: {
		flex: 1,
		flexDirection: 'column',
		justifyContent: "flex-end",
		textAlign: "right",
	},
	adminMsg: {
		width: "60%",
		flexDirection: 'column',
		alignItems: "center",
		justifyContent: "center",
		paddingHorizontal: (global.IS_IPAD ? 15 : 10),
		borderRadius: (global.IS_IPAD ? 10 : 5),
		padding: global.Gap_5,
		alignSelf: "center",
		backgroundColor: global.PINK_COLOR
	},
	messageTxt: {
		flexWrap: "wrap",
		textAlign: "left",
		alignItems: "flex-start",
		justifyContent: "flex-start"
	},
	fromMessageImg: {
		width: "60%",
		flexDirection: 'column',
		alignSelf: "flex-end",
		justifyContent: "flex-end",
		position: "relative",
		borderRadius: (global.IS_IPAD ? 10 : 5),
		padding: 0,
	},
	messagesImg: {
		width: '100%',
		height: (IS_IPAD ? 450 : 160),
		borderRadius: (global.IS_IPAD ? 10 : 5),
		resizeMode: "cover", // cover,contain,stretch,repeat,center
	},
	fromMessages: {
		width: "80%",
		flexDirection: 'column',
		alignSelf: "flex-end",
		justifyContent: "flex-end",
		position: "relative",
		paddingHorizontal: (global.IS_IPAD ? 15 : 10),
		borderRadius: (global.IS_IPAD ? 10 : 5),
		backgroundColor: global.CHAT_BOX_COLOR,
		padding: global.Gap_5,
	},
	toMessageImg: {
		width: "60%",
		flexDirection: 'column',
		alignSelf: "flex-start",
		justifyContent: "flex-start",
		position: "relative",
		borderRadius: (global.IS_IPAD ? 10 : 5),
		padding: 0,
	},
	toMessages: {
		width: "80%",
		flexDirection: 'column',
		alignSelf: "flex-start",
		justifyContent: "flex-start",
		position: "relative",
		paddingHorizontal: (global.IS_IPAD ? 15 : 10),
		borderRadius: (global.IS_IPAD ? 10 : 5),
		padding: global.Gap_5,
		backgroundColor: global.WHITE_COLOR,
	},
	megView: {
		flex: 1,
		flexDirection: 'column',
		marginBottom: global.Gap_10,
	},
	ratingSaveDescriprion: {
		//marginTop: 0,
		height: (global.IS_IPAD ? 150 : 110),
		width: '100%',
		fontSize: (global.IS_IPAD ? 24 : 14),
		fontFamily: global.DEFAULT_FONT,
		color: global.BLACK_COLOR,
		textAlignVertical: "top",
	},
	postShareInputview: {
		fontFamily: global.DEFAULT_FONT,
		fontSize: (global.IS_IPAD ? 28 : 18),
		color: global.BLACK_COLOR,
		paddingVertical: 0,
	},
	showImagesImage: {
		width: width,
		height: height,
		overflow: "hidden",
		resizeMode: "contain", // cover,contain,stretch,repeat,center
	},
	saveRatingCarView: {
		//marginLeft: global.Gap_5,
		width: width - global.Gap_5 - global.Gap_5,
		position: "relative",
		marginTop: global.Gap_5,
		marginLeft: global.Gap_5,
		borderRadius: global.Gap_10,
		alignItems: 'center',
		justifyContent: 'center',
	},
	wantedPostBtn: {
		marginRight: global.Gap_20,
	},
	postListViewItemImage: {
		width: (global.IS_IPAD ? 200 : 100),
		height: (global.IS_IPAD ? 100 : 60),
		borderRadius: (global.IS_IPAD ? 10 : 5),
		backgroundColor: global.FULL_LIGHT_GREY_COLOR,
		alignItems: 'flex-start',
		justifyContent: 'flex-start',
		overflow: "hidden",
		resizeMode: "cover", // cover,contain,stretch,repeat,center
	},
	postListViewItemOneImage: {
		width: (global.IS_IPAD ? 200 : 100),
		height: (global.IS_IPAD ? 200 : 105),
		borderRadius: (global.IS_IPAD ? 10 : 5),
		backgroundColor: global.FULL_LIGHT_GREY_COLOR,
		alignItems: 'flex-start',
		justifyContent: 'flex-start',
		overflow: "hidden",
		resizeMode: "contain", // cover,contain,stretch,repeat,center
	},
	postListViewItemSubImage: {
		width: ((global.IS_IPAD ? 200 : 100) / 2) - global.Gap_2,
		height: (global.IS_IPAD ? 150 : 80) / 2,
		borderRadius: (global.IS_IPAD ? 10 : 5),
		backgroundColor: global.FULL_LIGHT_GREY_COLOR,
		alignItems: 'flex-start',
		justifyContent: 'flex-start',
		overflow: "hidden",
		resizeMode: "cover", // cover,contain,stretch,repeat,center
	},
	buttonShadow: {
		shadowColor: global.BLACK_COLOR,
		shadowOffset: {
			width: 0,
			height: 2
		},
		shadowRadius: 5,
		shadowOpacity: 0.5
	},
	referralInputView: {
		marginTop: (global.IS_IPAD ? 10 : 5),
		paddingVertical: (global.IS_IPAD ? 20 : 15),
		paddingHorizontal: (global.IS_IPAD ? 15 : 10),
		borderRadius: (global.IS_IPAD ? 15 : 10),
		backgroundColor: global.WHITE_COLOR,
	},
	messagesFullImage: {
		width: '100%',
		height: '100%',
		resizeMode: "cover", // cover,contain,stretch,repeat,center
	},
	shareFacebookItem: {
		marginTop: (global.IS_IPAD ? 170 : 110),
		width: width - global.Gap_15 - global.Gap_15,
		paddingVertical: (global.IS_IPAD ? 15 : 10),
		borderRadius: global.Gap_10,
		flexDirection: "row",
		alignItems: 'center',
		justifyContent: 'center',
		backgroundColor: global.WHITE_COLOR,
	},
	shareFacebookItemImage: {
		width: (global.IS_IPAD ? 150 : 80),
		height: (global.IS_IPAD ? 100 : 60),
		borderRadius: (global.IS_IPAD ? 10 : 5),
		backgroundColor: global.FULL_LIGHT_GREY_COLOR,
		alignItems: 'flex-start',
		justifyContent: 'flex-start',
		overflow: "hidden",
		resizeMode: "cover", // cover,contain,stretch,repeat,center
	},
	shareFacebookItemOneImage: {
		width: (global.IS_IPAD ? 150 : 80),
		height: (global.IS_IPAD ? 200 : 105),
		borderRadius: (global.IS_IPAD ? 10 : 5),
		backgroundColor: global.FULL_LIGHT_GREY_COLOR,
		alignItems: 'flex-start',
		justifyContent: 'flex-start',
		overflow: "hidden",
		resizeMode: "cover", // cover,contain,stretch,repeat,center
	},
	shareFacebookItemSubImage: {
		width: ((global.IS_IPAD ? 150 : 80) / 2) - global.Gap_2,
		height: (global.IS_IPAD ? 150 : 80) / 2,
		borderRadius: (global.IS_IPAD ? 10 : 5),
		backgroundColor: global.FULL_LIGHT_GREY_COLOR,
		alignItems: 'flex-start',
		justifyContent: 'flex-start',
		overflow: "hidden",
		resizeMode: "cover", // cover,contain,stretch,repeat,center
	},
	homeTabBlurImage: {
		width: width,
		height: global.FULL_DISPLAY ? height / 1.7 : height / 2.1,
		alignItems: 'center',
		justifyContent: 'center',
		resizeMode: "cover", // cover,contain,stretch,repeat,center
	},
	homeViewItemImage: {
		overflow: "hidden",
		height: Platform.OS == 'ios' ? (global.IS_IPAD ? 180 : 100) : (global.IS_IPAD ? 180 : 90),
		width: (width - (global.IS_IPAD ? 20 : 15) - (global.IS_IPAD ? 20 : 15) - (global.IS_IPAD ? 20 : 15)) / 2,
		resizeMode: "cover", // cover,contain,stretch,repeat,center
		alignItems: 'center',
		justifyContent: 'center',
	},
	albumsListItemImage: {
		overflow: "hidden",
		height: (width - (global.IS_IPAD ? 20 : 15) - (global.IS_IPAD ? 20 : 15) - (global.IS_IPAD ? 20 : 15)) / 2,
		width: (width - (global.IS_IPAD ? 20 : 15) - (global.IS_IPAD ? 20 : 15) - (global.IS_IPAD ? 20 : 15)) / 2,
		resizeMode: "cover", // cover,contain,stretch,repeat,center
		alignItems: 'center',
		justifyContent: 'center',
	},
	recentlyPlayedAlbumsItemImage: {
		overflow: "hidden",
		height: (width - (global.IS_IPAD ? 20 : 15) - (global.IS_IPAD ? 20 : 15) - (global.IS_IPAD ? 20 : 15)) / 2.5,
		width: (width - (global.IS_IPAD ? 20 : 15) - (global.IS_IPAD ? 20 : 15) - (global.IS_IPAD ? 20 : 15)) / 2.5,
		resizeMode: "cover", // cover,contain,stretch,repeat,center
		alignItems: 'center',
		justifyContent: 'center',
	},
	qiCoilPlayerImage: {
		overflow: "hidden",
		height: width - (global.IS_IPAD ? 80 : 50) - (global.IS_IPAD ? 80 : 50),
		width: width - (global.IS_IPAD ? 80 : 50) - (global.IS_IPAD ? 80 : 50),
		borderRadius: (global.IS_IPAD ? 20 : 15),
		resizeMode: "cover", // cover,contain,stretch,repeat,center
		alignItems: 'center',
		justifyContent: 'center',
	},
	programsDetailsImage: {
		overflow: "hidden",
		height: (global.IS_IPAD ? 100 : 60),
		width: (global.IS_IPAD ? 100 : 60),
		borderRadius: (global.IS_IPAD ? 10 : 5),
		resizeMode: "cover", // cover,contain,stretch,repeat,center
	},
	videoTabItemImage: {
		width: (global.IS_IPAD ? 200 : 120),
		height: ((global.IS_IPAD ? 200 : 120) * 9) / 16,
		backgroundColor: global.FULL_LIGHT_GREY_COLOR,
		alignItems: 'flex-start',
		justifyContent: 'flex-start',
		overflow: "hidden",
		resizeMode: "cover", // cover,contain,stretch,repeat,center
	},
	albumsDetailsView: {
		position: "absolute",
		width: "100%",
		height: "100%",
		top: 0,
		left: 0,
		right: 0,
		bottom: 0,
		justifyContent: "center",
		alignItems: "center",
		// backgroundColor: "rgba(0,0,0,0.6)",
		// zIndex: 99,
	},
	downloadView: {
		position: "absolute",
		width: "100%",
		height: "100%",
		top: 0,
		left: 0,
		right: 0,
		bottom: 0,
		justifyContent: "center",
		alignItems: "center",
		backgroundColor: "rgba(255,255,255,0.4)",
		// zIndex: 99,
	},
	albumsDetailsImage: {
		overflow: "hidden",
		height: width / 2,
		width: width / 2,
		resizeMode: "cover", // cover,contain,stretch,repeat,center
	},
	subscribeAlbumImage: {
		overflow: "hidden",
		height: width / 2,
		width: width / 2,
		resizeMode: "cover", // cover,contain,stretch,repeat,center
	},
	aboutView: {
		width: width - (global.IS_IPAD ? 40 : 30) - (global.IS_IPAD ? 40 : 30),
		borderRadius: (global.IS_IPAD ? 15 : 10),
		backgroundColor: global.WHITE_COLOR,
	},
	searchInput: {
		fontSize: (global.IS_IPAD ? 26 : 16),
		fontFamily: global.DEFAULT_FONT,
		color: global.BLACK_COLOR,
		alignItems: "flex-start",
		paddingVertical: 0,
	},
	homeMoodComment: {
		height: (global.IS_IPAD ? 110 : 70),
		width: '85%',
		paddingHorizontal: (global.IS_IPAD ? 10 : 5),
		paddingVertical: 0,
		borderWidth: 1,
		alignItems: "flex-start",
		textAlignVertical: "top",
		fontSize: (global.IS_IPAD ? 26 : 16),
		fontFamily: global.DEFAULT_FONT,
		color: global.BLACK_COLOR,
		borderColor: DRAK_GREY_COLOR,
		backgroundColor: WHITE_COLOR,
	},


	/*** Typography ***/
	unreadCount: {
		fontFamily: global.DEFAULT_FONT_BOLD,
		fontSize: (global.IS_IPAD ? 17 : 7),
		lineHeight: (global.IS_IPAD ? 22 : 10),
	},
	matchesCount: {
		fontFamily: global.DEFAULT_FONT_BOLD,
		fontSize: (global.IS_IPAD ? 20 : 10),
		lineHeight: (global.IS_IPAD ? 26 : 14),
	},
	planNameFont: {
		fontFamily: global.DEFAULT_FONT,
		fontSize: (global.IS_IPAD ? 50 : 40),
		lineHeight: (global.IS_IPAD ? 56 : 44),
	},
	extraBigFont: {
		fontFamily: global.DEFAULT_FONT,
		fontSize: (global.IS_IPAD ? 50 : 40),
		lineHeight: (global.IS_IPAD ? 56 : 44),
	},
	bigFont: {
		fontFamily: global.DEFAULT_FONT,
		fontSize: (global.IS_IPAD ? 40 : 30),
		lineHeight: (global.IS_IPAD ? 46 : 34),
	},
	h1Big: {
		fontFamily: global.DEFAULT_FONT,
		fontSize: (global.IS_IPAD ? 36 : 26),
		lineHeight: (global.IS_IPAD ? 42 : 30),
	},
	h1Big2: {
		fontFamily: global.DEFAULT_FONT,
		fontSize: (global.IS_IPAD ? 34 : 24),
		lineHeight: (global.IS_IPAD ? 40 : 28),
	},
	h1: {
		fontFamily: global.DEFAULT_FONT,
		fontSize: (global.IS_IPAD ? 32 : 22),
		lineHeight: (global.IS_IPAD ? 38 : 26),
	},
	h2: {
		fontFamily: global.DEFAULT_FONT,
		fontSize: (global.IS_IPAD ? 30 : 20),
		lineHeight: (global.IS_IPAD ? 36 : 24),
	},
	h3: {
		fontFamily: global.DEFAULT_FONT,
		fontSize: (global.IS_IPAD ? 28 : 18),
		lineHeight: (global.IS_IPAD ? 34 : 22),
	},
	h4: {
		fontFamily: global.DEFAULT_FONT,
		fontSize: (global.IS_IPAD ? 26 : 16),
		lineHeight: (global.IS_IPAD ? 32 : 20),
	},
	h5: {
		fontFamily: global.DEFAULT_FONT,
		fontSize: (global.IS_IPAD ? 24 : 14),
		lineHeight: (global.IS_IPAD ? 30 : 18),
	},
	bodyFont: {
		fontFamily: global.DEFAULT_FONT,
		fontSize: (global.IS_IPAD ? 22 : 12),
		lineHeight: (global.IS_IPAD ? 28 : 16),
	},
	smallFont: {
		fontFamily: global.DEFAULT_FONT,
		fontSize: (global.IS_IPAD ? 20 : 10),
		lineHeight: (global.IS_IPAD ? 26 : 14),
	},
	extraSmallFont: {
		fontFamily: global.DEFAULT_FONT,
		fontSize: (global.IS_IPAD ? 18 : 8),
		lineHeight: (global.IS_IPAD ? 24 : 12),
	},

	/*** Icon Size ***/
	icon10: {
		width: (global.IS_IPAD ? 15 : 10),
		height: (global.IS_IPAD ? 15 : 10),
	},
	icon12: {
		width: (global.IS_IPAD ? 17 : 12),
		height: (global.IS_IPAD ? 17 : 12),
	},
	icon14: {
		width: (global.IS_IPAD ? 18 : 14),
		height: (global.IS_IPAD ? 18 : 14),
	},
	icon15: {
		width: (global.IS_IPAD ? 20 : 15),
		height: (global.IS_IPAD ? 20 : 15),
	},
	icon16: {
		width: (global.IS_IPAD ? 20 : 16),
		height: (global.IS_IPAD ? 20 : 16),
	},
	icon18: {
		width: (global.IS_IPAD ? 24 : 18),
		height: (global.IS_IPAD ? 24 : 18),
	},
	icon20: {
		width: (global.IS_IPAD ? 30 : 20),
		height: (global.IS_IPAD ? 30 : 20),
	},
	icon22: {
		width: (global.IS_IPAD ? 32 : 22),
		height: (global.IS_IPAD ? 32 : 22),
	},
	icon24: {
		width: (global.IS_IPAD ? 34 : 24),
		height: (global.IS_IPAD ? 34 : 24),
	},
	icon26: {
		width: (global.IS_IPAD ? 36 : 26),
		height: (global.IS_IPAD ? 36 : 26),
	},
	icon28: {
		width: (global.IS_IPAD ? 38 : 28),
		height: (global.IS_IPAD ? 38 : 28),
	},
	icon30: {
		width: (global.IS_IPAD ? 40 : 30),
		height: (global.IS_IPAD ? 40 : 30),
	},
	icon34: {
		width: (global.IS_IPAD ? 44 : 34),
		height: (global.IS_IPAD ? 44 : 34),
	},
	icon35: {
		width: (global.IS_IPAD ? 45 : 35),
		height: (global.IS_IPAD ? 45 : 35),
	},
	icon40: {
		width: (global.IS_IPAD ? 60 : 40),
		height: (global.IS_IPAD ? 60 : 40),
	},
	icon45: {
		width: (global.IS_IPAD ? 65 : 45),
		height: (global.IS_IPAD ? 65 : 45),
	},
	icon46: {
		width: (global.IS_IPAD ? 68 : 46),
		height: (global.IS_IPAD ? 68 : 46),
	},
	icon50: {
		width: (global.IS_IPAD ? 80 : 50),
		height: (global.IS_IPAD ? 80 : 50),
	},
	icon60: {
		width: (global.IS_IPAD ? 100 : 60),
		height: (global.IS_IPAD ? 100 : 60),
	},
	icon70: {
		width: (global.IS_IPAD ? 110 : 70),
		height: (global.IS_IPAD ? 110 : 70),
	},
});